### ISSUE TITLE
Missing tag and component.json

### ISSUE THREAD

**Issue by boennemann** [chaplinjs/downloads#2]
Due to the new gh-pages branch the component.json is missing. Is this a deliberate decision? Why is the old master branch gone?

> If you’re using Twitter Bower package manager, Chaplin is available there with bower install chaplin#0.7.0 [docs](http://chaplinjs.org/#downloads)

That's not correct, because there is no such [tag](https://github.com/chaplinjs/downloads/tree/0.7.0), also bower fails:

> bower error Could not find tag satisfying: chaplin#0.7.0
> There where errors, here's a summary of them:
> - chaplin Could not find tag satisfying: chaplin#0.7.0
>   The tag 0.7.0 could not be found within the repository

As raised in https://github.com/chaplinjs/chaplin/issues/426 it seems chaplin lacks a clear process for the release of new versions.

**Comment by paulmillr** [comment]
we’ve forgot to update tag, will do today

**Comment by mehcode** [comment]
Fixed it. I meant to do it yesterday. Apologies.

**Comment by boennemann** [comment]
thanks guys! great work
