### ISSUE TITLE
Allow Backbone 1.1.0 with Browserify

### ISSUE THREAD

**Issue by tuxracer** [chaplinjs/downloads#4]
The Backbone dependency in package.json should be `"backbone": "1.0.0 - 1.1.99"` This would require an `npm publish` which would in turn require a version bump. So this change should probably just be saved for the next release.

**Comment by paulmillr** [comment]
Backbone 1.1 is allowed with current version (~1.1).

**Comment by tuxracer** [comment]
The package.json dependency is set to `"backbone": "~1.0.0"`. So if you're using Chaplin with Browserify that makes the dep Backbone 1.0.*

**Comment by paulmillr** [comment]
hmm yes well that should be fixed then
