### ISSUE TITLE
Backbone Dependency

### ISSUE THREAD

**Issue by chrismcv** [chaplinjs/downloads#6]
Hi, 
The backbone 1.1.2 isn't yet merged on the components/backbone shim.  Now that backbone has component.json included in it, can we change the dependency to jashkenas/backbone?

Thanks,
Chris

**Comment by paulmillr** [comment]
![](http://www.newworldorderwar.com/wp-content/uploads/2010/12/obama-yes-we-can_04-nov-08.jpg)
